os: Visual Studio 2017 RC

environment:
  COVERALLS_REPO_TOKEN:
    secure: x41DSerLXKgGVbKIokF+zuR3eNRVJXsgJA6j5yggnCB8/TTyYfa/2euNflfGzCot
  SONARQUBE:
    secure: HinUSQVVcQgbGUw38sB8GgopaaXJkD1IDeXwNsTIHv/X/IQsQHS1icvTD1ZUjblP

before_build:
  - dotnet restore

build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"Qwack" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%SONARQUBE%"
  - msbuild "qwack.sln"
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=%SONARQUBE%"
  
before_test:
  - dotnet --info
  - VersionNumber.bat
  - dotnet restore

test_script:
  # Build sample
  - dotnet test test/Qwack.Core.Tests/Qwack.Core.Tests.csproj
  - dotnet test test/Qwack.Excel.Tests/Qwack.Excel.Tests.csproj
  - dotnet test test/Qwack.Math.Tests/Qwack.Math.Tests.csproj
  - dotnet test test/Qwack.Dates.Tests/Qwack.Dates.Tests.csproj
  - dotnet test test/Qwack.Core.Tests/Qwack.Core.Tests.csproj
  
after_test:
  # Build and pack source
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\OpenCover'))[0].FullName + '\tools\OpenCover.Console.exe' + ' -register:user -target:".\script\runtests.bat" -searchdirs:".\test\Qwack.Math.Tests\bin\Debug\netcoreapp1.1;.\test\Qwack.Dates.Tests\bin\Debug\netcoreapp1.1;.\test\Qwack.Core.Tests\bin\Debug\netcoreapp1.1" -oldstyle -output:coverage.xml -skipautoprops -returntargetcode -filter:"+[Qwack*]* -[*Tests]* -[*Benchmark]*"')
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\coveralls.io'))[0].FullName + '\tools\coveralls.net.exe' + ' --opencover coverage.xml')
  - dotnet pack -c Release src/Qwack.Math
  - dotnet pack -c Release src/Qwack.Math.Interpolation
  - dotnet pack -c Release src/Qwack.Dates
  - dotnet pack -c Release src/Qwack.Core
  - dotnet pack -c Release src/Qwack.Options
  - dotnet pack -c Release src/Qwack.Paths
  - dotnet pack -c Release src/Qwack.Providers
  - dotnet pack -c Release src/Qwack.Random
  - dotnet pack -c Release src/Qwack.Utils
  
artifacts:
  path: '**/*.nupkg'

deploy:  
- provider: NuGet
  server: https://www.myget.org/F/qwack/api/v2/package
  api_key:
    secure: 5mBb0A2rlwk1Iq6FEo94XSORm9etc3xPn0oLZ8dIJ6Hmm1G7quqf+Bz6fm+ft+FK
  skip_symbols: true
  on:
    branch: master