os: Visual Studio 2015
build: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: 9Flz1qTscHObl14SzMvP5PvOHXDf95W83hg6tUn1fg4Uovtu2tcSTexjpnlU/u/5

before_test:
  - dotnet --info
  - dotnet restore

test_script:
  # Build sample
  - dotnet test test/Qwack.Math.Tests
  - dotnet test test/Qwack.Dates.Tests
  - dotnet test test/Qwack.Core.Tests
  
after_test:
  # Build and pack source
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\OpenCover'))[0].FullName + '\tools\OpenCover.Console.exe' + ' -register:user -target:".\script\runtests.bat" -searchdirs:".\test\Qwack.Math.Tests\bin\Debug\netcoreapp1.0;.\test\Qwack.Dates.Tests\bin\Debug\netcoreapp1.0;.\test\Qwack.Core.Tests\bin\Debug\netcoreapp1.0" -oldstyle -output:coverage.xml -skipautoprops -returntargetcode -filter:"+[Qwack*]* -[*Tests]* -[*Benchmark]*"')
  - ps: iex ((Get-ChildItem ($env:USERPROFILE + '\.nuget\packages\coveralls.io'))[0].FullName + '\tools\coveralls.net.exe' + ' --opencover coverage.xml')
  - dotnet pack -c Release src/Qwack.Math --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/Qwack.Math.Interpolation --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/Qwack.Dates --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/Qwack.Core --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/Qwack.Options --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/Qwack.Path --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/Qwack.Providers --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/Qwack.Random --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/Qwack.Utils --version-suffix %APPVEYOR_BUILD_NUMBER%
  
artifacts:
  path: '**/*.nupkg'

deploy:  
- provider: NuGet
  server: https://www.myget.org/F/qwack/api/v2/package
  api_key:
    secure: 5mBb0A2rlwk1Iq6FEo94XSORm9etc3xPn0oLZ8dIJ6Hmm1G7quqf+Bz6fm+ft+FK
  skip_symbols: true
  on:
    branch: master